let defaultPr =
{
    "sheets": [{
        "name": "sheet1",
        "data": [{
            "cell": "A1",
            "css": "cell-customer01",
            "format": "text",
            "value": "請購單別"
        }, {
            "cell": "B1",
            "css": "cell-customer01",
            "format": "text",
            "value": "請購單號"
        }, {
            "cell": "C1",
            "css": "cell-customer09",
            "format": "text",
            "value": "請購部門"
        }, {
            "cell": "D1",
            "css": "cell-customer02",
            "format": "text",
            "value": "單據日期"
        }, {
            "cell": "E1",
            "css": "cell-customer02",
            "format": "text",
            "value": "需求日期"
        }, {
            "cell": "F1",
            "css": "cell-customer03",
            "format": "text",
            "value": "品號"
        }, {
            "cell": "G1",
            "css": "cell-customer03",
            "format": "text",
            "value": "品名"
        }, {
            "cell": "H1",
            "css": "cell-customer03",
            "format": "text",
            "value": "規格"
        }, {
            "cell": "I1",
            "css": "cell-customer04",
            "format": "text",
            "value": "庫別"
        }, {
            "cell": "J1",
            "css": "cell-customer05",
            "format": "text",
            "value": "請購數量"
        }, {
            "cell": "K1",
            "css": "cell-customer10",
            "format": "text",
            "value": "庫存數量"
        }, {
            "cell": "L1",
            "css": "cell-customer11",
            "format": "text",
            "value": "在途採購"
        }, {
            "cell": "M1",
            "css": "cell-customer05",
            "format": "text",
            "value": "請購單價"
        }, {
            "cell": "N1",
            "css": "cell-customer05",
            "format": "text",
            "value": "請購金額"
        }, {
            "cell": "O1",
            "css": "cell-customer06",
            "format": "text",
            "value": "請購幣別"
        }, {
            "cell": "P1",
            "css": "cell-customer06",
            "format": "text",
            "value": "請購單位"
        }, {
            "cell": "Q1",
            "css": "cell-customer07",
            "format": "text",
            "value": "參考訂單"
        }, {
            "cell": "R1",
            "css": "cell-customer08",
            "format": "text",
            "value": "供應商"
        }],
        "cols": [{
            "width": 120
        }, {
            "width": 182
        }, {
            "width": 150
        }, {
            "width": 120
        }, {
            "width": 120
        }, {
            "width": 204
        }, {
            "width": 204
        }, {
            "width": 150
        }, {
            "width": 120
        }, {
            "width": 120
        }, {
            "width": 120
        }, {
            "width": 120
        }, {
            "width": 120
        }, {
            "width": 120
        }, {
            "width": 120
        }, {
            "width": 120
        }, {
            "width": 200
        }, {
            "width": 200
        }],
        "rows": [{
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }, {
            "height": 32
        }]
    }],
    "styles": {
        "cell-customer01": {
            "white-space": "nowrap"
        },
        "cell-customer02": {
            "white-space": "nowrap"
        },
        "cell-customer03": {
            "white-space": "nowrap"
        },
        "cell-customer04": {
            "white-space": "nowrap"
        },
        "cell-customer05": {
            "white-space": "nowrap"
        },
        "cell-customer06": {
            "white-space": "nowrap"
        },
        "cell-customer07": {
            "white-space": "nowrap"
        }
    },
    "formats": [{
        "name": "Common",
        "id": "common",
        "mask": "",
        "example": "1500.31"
    }, {
        "name": "Number",
        "id": "number",
        "mask": "#,##0.00",
        "example": "1500.31"
    }, {
        "name": "Percent",
        "id": "percent",
        "mask": "#,##0.00%",
        "example": "15.0031"
    }, {
        "name": "Currency",
        "id": "currency",
        "mask": "$#,##0.00",
        "example": "1500.31"
    }, {
        "name": "Date",
        "id": "date",
        "mask": "mm-dd-yy",
        "example": "44490",
        "dateFormat": "%d/%m/%Y"
    }, {
        "name": "Time",
        "id": "time",
        "mask": "h:mm:ss am/pm",
        "example": "0.5625",
        "timeFormat": 12
    }, {
        "name": "Text",
        "id": "text",
        "mask": "@",
        "example": "some text"
    }]
};